// <auto-generated />
using MUN_Digital_Speaker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MUN_Digital_Speaker.Migrations
{
    [DbContext(typeof(MUN_Digital_SpeakerContext))]
    [Migration("20260213163305_councels")]
    partial class councels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MUN_Digital_Speaker.Models.Delegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmendmentPoints")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<int>("Login")
                        .HasColumnType("int");

                    b.Property<bool>("RequestedToSpeakECO")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestedToSpeakENV")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestedToSpeakGEN")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestedToSpeakHE")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestedToSpeakSEC")
                        .HasColumnType("bit");

                    b.Property<int?>("TimesSpoken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Delegation");
                });

            modelBuilder.Entity("MUN_Digital_Speaker.Models.Delegation", b =>
                {
                    b.OwnsMany("MUN_Digital_Speaker.Models.Amendment", "amendments", b1 =>
                        {
                            b1.Property<int>("DelegationId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Change")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ClauseNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Metadata")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ResolutionID")
                                .HasColumnType("int");

                            b1.HasKey("DelegationId", "Id");

                            b1.ToTable("Amendment");

                            b1.WithOwner()
                                .HasForeignKey("DelegationId");
                        });

                    b.Navigation("amendments");
                });
#pragma warning restore 612, 618
        }
    }
}
