// <auto-generated />
using MUN_Digital_Speaker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MUN_Digital_Speaker.Migrations
{
    [DbContext(typeof(MUN_Digital_SpeakerContext))]
    partial class MUN_Digital_SpeakerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MUN_Digital_Speaker.Models.Delegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequestedToSpeak")
                        .HasColumnType("bit");

                    b.Property<int?>("TimesSpoken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Delegation");
                });
#pragma warning restore 612, 618
        }
    }
}
